
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Label label1;

	private global::Gtk.HBox hbox3;

	private global::Gtk.CheckButton headerCheckBox;

	private global::Gtk.Entry datapathentry;

	private global::Gtk.Button getdatapathbutton;

	private global::Gtk.Label label4;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Entry ignorecolumnentry;

	private global::Gtk.Label label2;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Entry labelcolumnentry;

	private global::Gtk.Label label3;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Entry modeloutputentry;

	private global::Gtk.Label label5;

	private global::Gtk.SpinButton explorationTimeSpinner;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button buildbutton;

	private global::Gtk.Button ConvertDataButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Perley ML Model Builder");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Model Builder");
		this.vbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.headerCheckBox = new global::Gtk.CheckButton();
		this.headerCheckBox.CanFocus = true;
		this.headerCheckBox.Name = "headerCheckBox";
		this.headerCheckBox.Label = global::Mono.Unix.Catalog.GetString("Has Header?");
		this.headerCheckBox.Active = true;
		this.headerCheckBox.DrawIndicator = true;
		this.headerCheckBox.UseUnderline = true;
		this.hbox3.Add(this.headerCheckBox);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.headerCheckBox]));
		w2.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.datapathentry = new global::Gtk.Entry();
		this.datapathentry.CanFocus = true;
		this.datapathentry.Name = "datapathentry";
		this.datapathentry.IsEditable = true;
		this.datapathentry.InvisibleChar = '•';
		this.hbox3.Add(this.datapathentry);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.datapathentry]));
		w3.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.getdatapathbutton = new global::Gtk.Button();
		this.getdatapathbutton.CanFocus = true;
		this.getdatapathbutton.Name = "getdatapathbutton";
		this.getdatapathbutton.UseUnderline = true;
		this.getdatapathbutton.Label = global::Mono.Unix.Catalog.GetString("Data Path");
		this.hbox3.Add(this.getdatapathbutton);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.getdatapathbutton]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Ignore Colums --If Multiple Columns: Seperate With Comma (item1,item2)");
		this.vbox1.Add(this.label4);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label4]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.ignorecolumnentry = new global::Gtk.Entry();
		this.ignorecolumnentry.CanFocus = true;
		this.ignorecolumnentry.Name = "ignorecolumnentry";
		this.ignorecolumnentry.Text = global::Mono.Unix.Catalog.GetString("ID");
		this.ignorecolumnentry.IsEditable = true;
		this.ignorecolumnentry.InvisibleChar = '•';
		this.hbox4.Add(this.ignorecolumnentry);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.ignorecolumnentry]));
		w7.Position = 0;
		this.vbox1.Add(this.hbox4);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
		w8.Position = 3;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Label Column");
		this.vbox1.Add(this.label2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label2]));
		w9.Position = 4;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.labelcolumnentry = new global::Gtk.Entry();
		this.labelcolumnentry.CanFocus = true;
		this.labelcolumnentry.Name = "labelcolumnentry";
		this.labelcolumnentry.Text = "SentimentType";
		this.labelcolumnentry.IsEditable = true;
		this.labelcolumnentry.InvisibleChar = '•';
		this.hbox5.Add(this.labelcolumnentry);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.labelcolumnentry]));
		w10.Position = 0;
		this.vbox1.Add(this.hbox5);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
		w11.Position = 5;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Classification Type");
		this.vbox1.Add(this.label3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label3]));
		w12.Position = 6;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.modeloutputentry = new global::Gtk.Entry();
		this.modeloutputentry.CanFocus = true;
		this.modeloutputentry.Name = "modeloutputentry";
		this.modeloutputentry.Text = global::Mono.Unix.Catalog.GetString("multiclass-classification");
		this.modeloutputentry.IsEditable = true;
		this.modeloutputentry.InvisibleChar = '•';
		this.hbox6.Add(this.modeloutputentry);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.modeloutputentry]));
		w13.Position = 0;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Max Exploration Time: ");
		this.hbox6.Add(this.label5);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label5]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.explorationTimeSpinner = new global::Gtk.SpinButton(0D, 540D, 1D);
		this.explorationTimeSpinner.CanFocus = true;
		this.explorationTimeSpinner.Name = "explorationTimeSpinner";
		this.explorationTimeSpinner.Adjustment.PageIncrement = 10D;
		this.explorationTimeSpinner.ClimbRate = 1D;
		this.explorationTimeSpinner.Numeric = true;
		this.explorationTimeSpinner.Value = 10D;
		this.hbox6.Add(this.explorationTimeSpinner);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.explorationTimeSpinner]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		this.vbox1.Add(this.hbox6);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox6]));
		w16.Position = 7;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buildbutton = new global::Gtk.Button();
		this.buildbutton.CanFocus = true;
		this.buildbutton.Name = "buildbutton";
		this.buildbutton.UseUnderline = true;
		this.buildbutton.Label = global::Mono.Unix.Catalog.GetString("Build ");
		this.hbox1.Add(this.buildbutton);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buildbutton]));
		w17.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.ConvertDataButton = new global::Gtk.Button();
		this.ConvertDataButton.CanFocus = true;
		this.ConvertDataButton.Name = "ConvertDataButton";
		this.ConvertDataButton.UseUnderline = true;
		this.ConvertDataButton.Label = global::Mono.Unix.Catalog.GetString("Convert Json");
		this.hbox1.Add(this.ConvertDataButton);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ConvertDataButton]));
		w18.Position = 1;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w19.Position = 8;
		w19.Expand = false;
		w19.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 664;
		this.DefaultHeight = 290;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
