
// This file has been generated by the GUI designer. Do not modify.
namespace TestApp
{
	public partial class DataConverterWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label2;

		private global::Gtk.Entry dataSourceEntry;

		private global::Gtk.Button openFileButton;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label4;

		private global::Gtk.Entry outputPathEntry;

		private global::Gtk.Button openFolderButton;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label3;

		private global::Gtk.Entry newFileNameEntry;

		private global::Gtk.Label label5;

		private global::Gtk.Entry PropertiesToAddEntry;

		private global::Gtk.Button ConvertButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget TestApp.DataConverterWindow
			this.Name = "TestApp.DataConverterWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("DataConverterWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child TestApp.DataConverterWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("JSON To TSV Converter");
			this.vbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Data Source:");
			this.hbox1.Add(this.label2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.dataSourceEntry = new global::Gtk.Entry();
			this.dataSourceEntry.CanFocus = true;
			this.dataSourceEntry.Name = "dataSourceEntry";
			this.dataSourceEntry.IsEditable = true;
			this.dataSourceEntry.InvisibleChar = '•';
			this.hbox1.Add(this.dataSourceEntry);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.dataSourceEntry]));
			w3.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.openFileButton = new global::Gtk.Button();
			this.openFileButton.CanFocus = true;
			this.openFileButton.Name = "openFileButton";
			this.openFileButton.UseUnderline = true;
			this.openFileButton.Label = global::Mono.Unix.Catalog.GetString("Open File");
			this.hbox1.Add(this.openFileButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.openFileButton]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Ouput Path");
			this.hbox3.Add(this.label4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label4]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.outputPathEntry = new global::Gtk.Entry();
			this.outputPathEntry.CanFocus = true;
			this.outputPathEntry.Name = "outputPathEntry";
			this.outputPathEntry.IsEditable = true;
			this.outputPathEntry.InvisibleChar = '•';
			this.hbox3.Add(this.outputPathEntry);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.outputPathEntry]));
			w7.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.openFolderButton = new global::Gtk.Button();
			this.openFolderButton.CanFocus = true;
			this.openFolderButton.Name = "openFolderButton";
			this.openFolderButton.UseUnderline = true;
			this.openFolderButton.Label = global::Mono.Unix.Catalog.GetString("Open Folder");
			this.hbox3.Add(this.openFolderButton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.openFolderButton]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("New File Name");
			this.hbox2.Add(this.label3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label3]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.newFileNameEntry = new global::Gtk.Entry();
			this.newFileNameEntry.CanFocus = true;
			this.newFileNameEntry.Name = "newFileNameEntry";
			this.newFileNameEntry.IsEditable = true;
			this.newFileNameEntry.InvisibleChar = '•';
			this.hbox2.Add(this.newFileNameEntry);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.newFileNameEntry]));
			w11.Position = 1;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString(" Add Data Properties To Add, Separate with commas --> ID,SentimentType,Statement " +
					"");
			this.vbox1.Add(this.label5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label5]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.PropertiesToAddEntry = new global::Gtk.Entry();
			this.PropertiesToAddEntry.CanFocus = true;
			this.PropertiesToAddEntry.Name = "PropertiesToAddEntry";
			this.PropertiesToAddEntry.IsEditable = true;
			this.PropertiesToAddEntry.InvisibleChar = '•';
			this.vbox1.Add(this.PropertiesToAddEntry);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.PropertiesToAddEntry]));
			w14.Position = 5;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.ConvertButton = new global::Gtk.Button();
			this.ConvertButton.CanFocus = true;
			this.ConvertButton.Name = "ConvertButton";
			this.ConvertButton.UseUnderline = true;
			this.ConvertButton.Label = global::Mono.Unix.Catalog.GetString("Convert");
			this.vbox1.Add(this.ConvertButton);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.ConvertButton]));
			w15.Position = 6;
			w15.Expand = false;
			w15.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 570;
			this.DefaultHeight = 268;
			this.Show();
		}
	}
}
