
// This file has been generated by the GUI designer. Do not modify.
namespace TestApp
{
	public partial class MSGConverterWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Entry DatapathEntry;

		private global::Gtk.Button getDatapathButton;

		private global::Gtk.Button StartConvertButton;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.Entry DataViewEntry;

		private global::Gtk.HBox hbox2;

		private global::Gtk.CheckButton QuestionOrStatmentCheckbox;

		private global::Gtk.Label label3;

		private global::Gtk.Entry questionStatementTypeEntry;

		private global::Gtk.Label label2;

		private global::Gtk.Entry SentimentTypeEntry;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Button NextButton;

		private global::Gtk.Button SaveButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget TestApp.MSGConverterWindow
			this.Name = "TestApp.MSGConverterWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("MSGConverterWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child TestApp.MSGConverterWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Training Data Builder");
			this.vbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.DatapathEntry = new global::Gtk.Entry();
			this.DatapathEntry.CanFocus = true;
			this.DatapathEntry.Name = "DatapathEntry";
			this.DatapathEntry.IsEditable = true;
			this.DatapathEntry.InvisibleChar = '•';
			this.hbox1.Add(this.DatapathEntry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.DatapathEntry]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.getDatapathButton = new global::Gtk.Button();
			this.getDatapathButton.CanFocus = true;
			this.getDatapathButton.Name = "getDatapathButton";
			this.getDatapathButton.UseUnderline = true;
			this.getDatapathButton.Label = global::Mono.Unix.Catalog.GetString("Open Data");
			this.hbox1.Add(this.getDatapathButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.getDatapathButton]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.StartConvertButton = new global::Gtk.Button();
			this.StartConvertButton.CanFocus = true;
			this.StartConvertButton.Name = "StartConvertButton";
			this.StartConvertButton.UseUnderline = true;
			this.StartConvertButton.Label = global::Mono.Unix.Catalog.GetString("Start");
			this.hbox1.Add(this.StartConvertButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.StartConvertButton]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w6 = new global::Gtk.Viewport();
			w6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.DataViewEntry = new global::Gtk.Entry();
			this.DataViewEntry.CanFocus = true;
			this.DataViewEntry.Name = "DataViewEntry";
			this.DataViewEntry.IsEditable = true;
			this.DataViewEntry.InvisibleChar = '•';
			w6.Add(this.DataViewEntry);
			this.GtkScrolledWindow.Add(w6);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w9.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.QuestionOrStatmentCheckbox = new global::Gtk.CheckButton();
			this.QuestionOrStatmentCheckbox.CanFocus = true;
			this.QuestionOrStatmentCheckbox.Name = "QuestionOrStatmentCheckbox";
			this.QuestionOrStatmentCheckbox.Label = global::Mono.Unix.Catalog.GetString("Question?");
			this.QuestionOrStatmentCheckbox.DrawIndicator = true;
			this.QuestionOrStatmentCheckbox.UseUnderline = true;
			this.hbox2.Add(this.QuestionOrStatmentCheckbox);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.QuestionOrStatmentCheckbox]));
			w10.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Question or Statement Type:");
			this.hbox2.Add(this.label3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label3]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.questionStatementTypeEntry = new global::Gtk.Entry();
			this.questionStatementTypeEntry.CanFocus = true;
			this.questionStatementTypeEntry.Name = "questionStatementTypeEntry";
			this.questionStatementTypeEntry.IsEditable = true;
			this.questionStatementTypeEntry.InvisibleChar = '•';
			this.hbox2.Add(this.questionStatementTypeEntry);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.questionStatementTypeEntry]));
			w12.Position = 2;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Sentiment Type");
			this.hbox2.Add(this.label2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label2]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.SentimentTypeEntry = new global::Gtk.Entry();
			this.SentimentTypeEntry.CanFocus = true;
			this.SentimentTypeEntry.Name = "SentimentTypeEntry";
			this.SentimentTypeEntry.IsEditable = true;
			this.SentimentTypeEntry.InvisibleChar = '•';
			this.hbox2.Add(this.SentimentTypeEntry);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.SentimentTypeEntry]));
			w14.Position = 4;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w15.Position = 3;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.NextButton = new global::Gtk.Button();
			this.NextButton.CanFocus = true;
			this.NextButton.Name = "NextButton";
			this.NextButton.UseUnderline = true;
			this.NextButton.Label = global::Mono.Unix.Catalog.GetString("Next Item");
			this.hbox3.Add(this.NextButton);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.NextButton]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.SaveButton = new global::Gtk.Button();
			this.SaveButton.CanFocus = true;
			this.SaveButton.Name = "SaveButton";
			this.SaveButton.UseUnderline = true;
			this.SaveButton.Label = global::Mono.Unix.Catalog.GetString("Save");
			this.hbox3.Add(this.SaveButton);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.SaveButton]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w18.Position = 4;
			w18.Expand = false;
			w18.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 945;
			this.DefaultHeight = 471;
			this.Show();
		}
	}
}
